#include "gui_css.h"

static const char *CSS =
/* ── Color palette ─────────────────────────────────────────── */
"@define-color bg_primary    #ffffff;"
"@define-color bg_secondary  #f5f5f5;"
"@define-color bg_tertiary   #ebebeb;"
"@define-color bg_input      #fafafa;"
"@define-color accent        #ff9800;"
"@define-color accent_dark   #e65100;"
"@define-color accent_glow   #ffb74d;"
"@define-color danger        #d32f2f;"
"@define-color success       #2e7d32;"
"@define-color warning       #ff9800;"
"@define-color text_bright   #1a1a1a;"
"@define-color text_dim      #757575;"
"@define-color border        #d0d0d0;"
"@define-color border_focus  #ff9800;"
"\n"

/* ── Window / header ───────────────────────────────────────── */
"window, .background {"
"  background: @bg_primary;"
"  color: @text_bright;"
"}"
"headerbar {"
"  background: #f0f0f0;"
"  border-bottom: 1px solid @border;"
"  color: @text_bright;"
"  min-height: 40px;"
"}"
"headerbar .title {"
"  color: @accent_dark;"
"  font-weight: bold;"
"  font-size: 14px;"
"}"
"headerbar .subtitle {"
"  color: @text_dim;"
"  font-size: 10px;"
"}"
"\n"

/* ── Mode navigation buttons ───────────────────────────────── */
".mode-btn {"
"  background: transparent;"
"  border: 1px solid transparent;"
"  border-radius: 6px;"
"  color: @text_dim;"
"  padding: 6px 16px;"
"  font-weight: 600;"
"  font-size: 11px;"
"  min-width: 80px;"
"}"
".mode-btn:hover {"
"  background: alpha(@success, 0.1);"
"  color: @success;"
"  border-color: alpha(@success, 0.3);"
"}"
".mode-active {"
"  background: alpha(@success, 0.12);"
"  border: 1px solid @success;"
"  color: @success;"
"  border-radius: 6px;"
"  padding: 6px 16px;"
"  font-weight: 600;"
"  font-size: 11px;"
"  min-width: 80px;"
"}"
"\n"

/* ── Action buttons (GREEN) ────────────────────────────────── */
".act-btn {"
"  background: #2e7d32;"
"  color: white;"
"  border: none;"
"  border-radius: 5px;"
"  padding: 8px 20px;"
"  font-weight: bold;"
"  font-size: 12px;"
"}"
".act-btn:hover {"
"  background: #388e3c;"
"}"
".act-btn:disabled {"
"  background: alpha(#2e7d32, 0.3);"
"  color: alpha(white, 0.5);"
"}"
".stop-btn {"
"  background: @danger;"
"  color: white;"
"  border: none;"
"  border-radius: 5px;"
"  padding: 8px 20px;"
"  font-weight: bold;"
"  font-size: 12px;"
"}"
".stop-btn:hover {"
"  background: #e53935;"
"}"
".sec-btn {"
"  background: @bg_tertiary;"
"  color: @text_bright;"
"  border: 1px solid @border;"
"  border-radius: 5px;"
"  padding: 5px 12px;"
"  font-size: 11px;"
"}"
".sec-btn:hover {"
"  border-color: @success;"
"  background: alpha(@success, 0.08);"
"}"
".cp-btn {"
"  background: alpha(@accent, 0.1);"
"  color: @accent_dark;"
"  border: 1px solid @accent;"
"  border-radius: 5px;"
"  padding: 5px 14px;"
"  font-weight: bold;"
"  font-size: 11px;"
"}"
".cp-btn:hover {"
"  background: alpha(@accent, 0.25);"
"}"
".warn-btn {"
"  background: alpha(@warning, 0.12);"
"  color: @accent_dark;"
"  border: 1px solid alpha(@warning, 0.5);"
"  border-radius: 5px;"
"  padding: 5px 12px;"
"  font-size: 11px;"
"}"
".warn-btn:hover {"
"  background: alpha(@warning, 0.25);"
"}"
"\n"

/* ── Status / info boxes ───────────────────────────────────── */
".status-box {"
"  background: @bg_secondary;"
"  border: 1px solid @border;"
"  border-radius: 8px;"
"  padding: 14px;"
"}"
".addr-lbl {"
"  background: alpha(@success, 0.08);"
"  border: 1px solid alpha(@success, 0.4);"
"  border-radius: 5px;"
"  padding: 8px 14px;"
"  font-family: monospace;"
"  font-size: 12px;"
"  color: @success;"
"}"
".fileid-lbl {"
"  background: alpha(@accent, 0.08);"
"  border: 1px solid alpha(@accent, 0.4);"
"  border-radius: 5px;"
"  padding: 8px 14px;"
"  font-family: monospace;"
"  font-size: 10px;"
"  color: @accent_dark;"
"}"
"\n"

/* ── Drag zone ─────────────────────────────────────────────── */
".drag-zone {"
"  border: 2px dashed @border;"
"  border-radius: 10px;"
"  padding: 36px;"
"  background: alpha(@bg_tertiary, 0.5);"
"}"
".drag-zone:hover {"
"  border-color: @success;"
"  background: alpha(@success, 0.05);"
"}"
".drag-text {"
"  color: @text_dim;"
"  font-size: 13px;"
"}"
"\n"

/* ── Log area ──────────────────────────────────────────────── */
".log-area {"
"  background: #f9f9f9;"
"  color: #2e7d32;"
"  font-family: \"Source Code Pro\", \"DejaVu Sans Mono\", monospace;"
"  font-size: 10px;"
"  border: 1px solid @border;"
"  border-radius: 5px;"
"  padding: 6px;"
"}"
"\n"

/* ── Tree views ────────────────────────────────────────────── */
"treeview {"
"  background: @bg_secondary;"
"  color: @text_bright;"
"}"
"treeview:selected {"
"  background: alpha(@success, 0.2);"
"  color: @text_bright;"
"}"
"treeview header button {"
"  background: @bg_primary;"
"  color: @text_dim;"
"  border: none;"
"  border-bottom: 1px solid @border;"
"  font-weight: bold;"
"  font-size: 10px;"
"  padding: 4px 8px;"
"}"
"\n"

/* ── Progress bar ──────────────────────────────────────────── */
"progressbar trough {"
"  background: @bg_tertiary;"
"  border-radius: 3px;"
"  min-height: 6px;"
"}"
"progressbar progress {"
"  background: @success;"
"  border-radius: 3px;"
"  min-height: 6px;"
"}"
"\n"

/* ── Scrolled window / entry ───────────────────────────────── */
"scrolledwindow {"
"  border: 1px solid @border;"
"  border-radius: 5px;"
"  background: @bg_secondary;"
"}"
"entry {"
"  background: @bg_input;"
"  color: @text_bright;"
"  border: 1px solid @border;"
"  border-radius: 5px;"
"  padding: 7px 10px;"
"  font-size: 12px;"
"  caret-color: @accent;"
"}"
"entry:focus {"
"  border-color: @border_focus;"
"}"
"\n"

/* ── Labels / utility classes ──────────────────────────────── */
".sec-title {"
"  color: @text_bright;"
"  font-weight: bold;"
"  font-size: 12px;"
"}"
".dim-text {"
"  color: @text_dim;"
"  font-size: 11px;"
"}"
".stat-num {"
"  color: @accent_dark;"
"  font-weight: bold;"
"  font-size: 16px;"
"}"
".circuit-label {"
"  color: @accent;"
"  font-size: 11px;"
"  font-family: monospace;"
"}"
".pwd-entry {"
"  background: alpha(@danger, 0.05);"
"  border: 1px solid alpha(@danger, 0.3);"
"  border-radius: 5px;"
"  padding: 7px 10px;"
"  font-size: 12px;"
"  color: @text_bright;"
"  caret-color: @danger;"
"}"
".pwd-entry:focus {"
"  border-color: @danger;"
"}"
"separator {"
"  background: @border;"
"  min-height: 1px;"
"}"
;

const char *gui_get_css_theme(void)
{
    return CSS;
}