/*
 * SecureDrop — Encrypted File Sharing over Tor
 * Copyright (C) 2026  Abinav
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#include "gui_css.h"

static const char *CSS =
/* ── Color palette ─────────────────────────────────────────── */
"@define-color bg_primary    #ffffff;"
"@define-color bg_secondary  #f5f5f5;"
"@define-color bg_tertiary   #ebebeb;"
"@define-color bg_input      #fafafa;"
"@define-color sidebar_bg    #fafaf8;"
"@define-color sidebar_border #e8e8e4;"
"@define-color accent        #ff9800;"
"@define-color accent_dark   #e65100;"
"@define-color accent_glow   #ffb74d;"
"@define-color danger        #d32f2f;"
"@define-color success       #2e7d32;"
"@define-color warning       #ff9800;"
"@define-color text_bright   #1a1a1a;"
"@define-color text_dim      #757575;"
"@define-color border        #e0e0e0;"
"@define-color border_focus  #ff9800;"
"\n"

/* ── Window / header ───────────────────────────────────────── */
"window, .background {"
"  background: @bg_secondary;"
"  color: @text_bright;"
"}"
"headerbar {"
"  background: @bg_secondary;"
"  border-bottom: none;"
"  color: @text_bright;"
"  min-height: 0;"
"  padding: 0;"
"  margin: 0;"
"}"
"\n"

/* ── Sidebar ───────────────────────────────────────────────── */
".sidebar {"
"  background: @sidebar_bg;"
"  border-right: none;"
"  border-radius: 16px;"
"  padding: 6px 0;"
"  margin: 8px 0 8px 8px;"
"}"
".sidebar-brand {"
"  padding: 16px 18px 4px 18px;"
"}"
".sidebar-brand-title {"
"  color: @accent;"
"  font-weight: 800;"
"  font-size: 15px;"
"}"
".sidebar-brand-icon {"
"  color: @accent;"
"  font-size: 16px;"
"}"
".sidebar-info {"
"  color: @text_dim;"
"  font-size: 8px;"
"  padding: 2px 18px 12px 18px;"
"}"
"\n"

/* ── Sidebar navigation buttons ────────────────────────────── */
".sidebar-nav-btn {"
"  background: transparent;"
"  border: none;"
"  border-left: 3px solid transparent;"
"  border-radius: 8px;"
"  color: #555555;"
"  padding: 10px 18px;"
"  font-weight: 500;"
"  font-size: 12px;"
"  min-height: 18px;"
"  margin: 3px 8px 3px 8px;"
"}"
".sidebar-nav-btn:hover {"
"  background: alpha(@success, 0.06);"
"  color: @success;"
"}"
".sidebar-nav-active {"
"  background: alpha(@success, 0.08);"
"  border: none;"
"  border-left: 3px solid @success;"
"  border-radius: 8px;"
"  color: @success;"
"  padding: 10px 18px;"
"  font-weight: 600;"
"  font-size: 12px;"
"  min-height: 18px;"
"  margin: 3px 8px 3px 8px;"
"}"
".sidebar-nav-active:hover {"
"  background: alpha(@success, 0.12);"
"}"
".sidebar-footer {"
"  color: @text_dim;"
"  font-size: 8px;"
"  padding: 8px 14px;"
"}"
"\n"

/* ── Content wrapper ───────────────────────────────────────── */
".content-wrapper {"
"  background: @bg_primary;"
"  border-radius: 14px;"
"  padding: 20px;"
"  margin: 8px 8px 8px 4px;"
"}"
"\n"

/* ── Action buttons (GREEN) ────────────────────────────────── */
".act-btn {"
"  background: #2e7d32;"
"  color: white;"
"  border: none;"
"  border-radius: 6px;"
"  padding: 8px 22px;"
"  font-weight: bold;"
"  font-size: 12px;"
"}"
".act-btn:hover {"
"  background: #388e3c;"
"}"
".act-btn:disabled {"
"  background: alpha(#2e7d32, 0.3);"
"  color: alpha(white, 0.5);"
"}"
".stop-btn {"
"  background: @danger;"
"  color: #ffffff;"
"  border: none;"
"  border-radius: 6px;"
"  padding: 8px 22px;"
"  font-weight: bold;"
"  font-size: 12px;"
"}"
".stop-btn:hover {"
"  background: #e53935;"
"  color: #ffffff;"
"}"
".stop-btn label {"
"  color: #ffffff;"
"}"
".stop-btn:hover label {"
"  color: #ffffff;"
"}"
".sec-btn {"
"  background: @bg_primary;"
"  color: @text_bright;"
"  border: 1px solid @border;"
"  border-radius: 6px;"
"  padding: 6px 14px;"
"  font-size: 11px;"
"}"
".sec-btn:hover {"
"  border-color: @success;"
"  background: alpha(@success, 0.05);"
"}"
".cp-btn {"
"  background: alpha(@accent, 0.1);"
"  color: @accent_dark;"
"  border: 1px solid @accent;"
"  border-radius: 6px;"
"  padding: 5px 14px;"
"  font-weight: bold;"
"  font-size: 11px;"
"}"
".cp-btn:hover {"
"  background: alpha(@accent, 0.25);"
"}"
".warn-btn {"
"  background: alpha(@warning, 0.12);"
"  color: @accent_dark;"
"  border: 1px solid alpha(@warning, 0.5);"
"  border-radius: 6px;"
"  padding: 5px 14px;"
"  font-size: 11px;"
"}"
".warn-btn:hover {"
"  background: alpha(@warning, 0.25);"
"}"
"\n"

/* ── Server Active badge ───────────────────────────────────── */
".server-active-badge {"
"  background: @success;"
"  color: white;"
"  border-radius: 10px;"
"  padding: 4px 14px;"
"  font-weight: bold;"
"  font-size: 10px;"
"}"
".server-starting-badge {"
"  background: @accent;"
"  color: white;"
"  border-radius: 10px;"
"  padding: 4px 14px;"
"  font-weight: bold;"
"  font-size: 10px;"
"}"
"\n"

/* ── Status / info boxes ───────────────────────────────────── */
".status-box {"
"  background: @bg_secondary;"
"  border: 1px solid @border;"
"  border-radius: 10px;"
"  padding: 14px;"
"}"
".status-bar {"
"  background: alpha(@success, 0.04);"
"  border: 1px solid alpha(@success, 0.15);"
"  border-radius: 10px;"
"  padding: 10px 16px;"
"}"
".addr-lbl {"
"  background: @bg_secondary;"
"  border: 1px solid @border;"
"  border-radius: 6px;"
"  padding: 6px 12px;"
"  font-family: monospace;"
"  font-size: 11px;"
"  color: @text_bright;"
"}"
".fileid-lbl {"
"  background: alpha(@accent, 0.08);"
"  border: 1px solid alpha(@accent, 0.4);"
"  border-radius: 6px;"
"  padding: 8px 14px;"
"  font-family: monospace;"
"  font-size: 10px;"
"  color: @accent_dark;"
"}"
"\n"

/* ── Drag zone ─────────────────────────────────────────────── */
".drag-zone {"
"  border: 2px dashed #d4d4d4;"
"  border-radius: 12px;"
"  padding: 20px;"
"  background: alpha(@bg_tertiary, 0.2);"
"}"
".drag-zone:hover {"
"  border-color: @success;"
"  background: alpha(@success, 0.03);"
"}"
".drag-text {"
"  color: @text_dim;"
"  font-size: 12px;"
"}"
".drag-icon {"
"  color: #c0c0c0;"
"}"
".drag-subtext {"
"  color: #b0b0b0;"
"  font-size: 10px;"
"}"
"\n"

/* ── Downloads label ───────────────────────────────────────── */
".dl-label {"
"  color: @accent;"
"  font-weight: bold;"
"  font-size: 12px;"
"}"
"\n"

/* ── Log area ──────────────────────────────────────────────── */
".log-area {"
"  background: #f7f7f7;"
"  color: #2e7d32;"
"  font-family: \"Source Code Pro\", \"DejaVu Sans Mono\", monospace;"
"  font-size: 10px;"
"  padding: 8px;"
"}"
".log-scroll {"
"  background: #f7f7f7;"
"  border: 1px solid @border;"
"  border-radius: 8px;"
"}"
"textview {"
"  background: #f7f7f7;"
"}"
"textview text {"
"  background: #f7f7f7;"
"  color: #2e7d32;"
"}"
"\n"

/* ── Tree views ────────────────────────────────────────────── */
"treeview {"
"  background: @bg_primary;"
"  color: @text_bright;"
"}"
"treeview:selected {"
"  background: alpha(@success, 0.12);"
"  color: @text_bright;"
"}"
"treeview header button {"
"  background: @bg_primary;"
"  color: @text_dim;"
"  border: none;"
"  border-bottom: 1px solid @border;"
"  font-weight: bold;"
"  font-size: 10px;"
"  padding: 4px 8px;"
"}"
"\n"

/* ── Progress bar ──────────────────────────────────────────── */
"progressbar trough {"
"  background: @bg_tertiary;"
"  border-radius: 4px;"
"  min-height: 6px;"
"}"
"progressbar progress {"
"  background: @success;"
"  border-radius: 4px;"
"  min-height: 6px;"
"}"
"\n"

/* ── Scrolled window / entry ───────────────────────────────── */
"scrolledwindow {"
"  border: 1px solid @border;"
"  border-radius: 8px;"
"  background: @bg_primary;"
"}"
"entry {"
"  background: @bg_primary;"
"  color: @text_bright;"
"  border: 1px solid @border;"
"  border-radius: 6px;"
"  padding: 8px 12px;"
"  font-size: 12px;"
"  caret-color: @accent;"
"}"
"entry:focus {"
"  border-color: @border_focus;"
"}"
"\n"

/* ── Labels / utility classes ──────────────────────────────── */
".sec-title {"
"  color: @text_bright;"
"  font-weight: bold;"
"  font-size: 17px;"
"}"
".dim-text {"
"  color: @text_dim;"
"  font-size: 11px;"
"}"
".stat-num {"
"  color: @accent_dark;"
"  font-weight: bold;"
"  font-size: 16px;"
"}"
".circuit-label {"
"  color: @accent;"
"  font-size: 11px;"
"  font-family: monospace;"
"}"
".pwd-entry {"
"  background: alpha(@danger, 0.03);"
"  border: 1px solid alpha(@danger, 0.2);"
"  border-radius: 6px;"
"  padding: 8px 12px;"
"  font-size: 12px;"
"  color: @text_bright;"
"  caret-color: @danger;"
"}"
".pwd-entry:focus {"
"  border-color: @danger;"
"}"
"separator {"
"  background: alpha(@border, 0.5);"
"  min-height: 1px;"
"}"
"\n"

/* ── Subtitle text under page headers ──────────────────────── */
".page-subtitle {"
"  color: @success;"
"  font-size: 11px;"
"}"

/* ── Frame borders (for GtkFrame) ──────────────────────────── */
"frame {"
"  border-radius: 10px;"
"  border: 1px solid @border;"
"  padding: 4px;"
"}"
"frame > label {"
"  color: @accent_dark;"
"  font-weight: bold;"
"  font-size: 12px;"
"}"
;

const char *gui_get_css_theme(void)
{
    return CSS;
}