#include "gui_css.h"

static const char *CSS =
/* ── Color palette ─────────────────────────────────────────── */
"@define-color bg_primary    #0a0a1a;"
"@define-color bg_secondary  #111128;"
"@define-color bg_tertiary   #1a1a3e;"
"@define-color bg_input      #0d0d24;"
"@define-color accent        #4fc3f7;"
"@define-color accent_dark   #0288d1;"
"@define-color accent_glow   #29b6f6;"
"@define-color danger        #ef5350;"
"@define-color success       #66bb6a;"
"@define-color warning       #ffa726;"
"@define-color text_bright   #e0e0e8;"
"@define-color text_dim      #707090;"
"@define-color border        #1e1e40;"
"@define-color border_focus  #4fc3f7;"
"\n"

/* ── Window / header ───────────────────────────────────────── */
"window, .background {"
"  background: @bg_primary;"
"  color: @text_bright;"
"}"
"headerbar {"
"  background: @bg_secondary;"
"  border-bottom: 1px solid @accent_dark;"
"  color: @text_bright;"
"  min-height: 40px;"
"}"
"headerbar .title {"
"  color: @accent;"
"  font-weight: bold;"
"  font-size: 14px;"
"}"
"headerbar .subtitle {"
"  color: @text_dim;"
"  font-size: 10px;"
"}"
"\n"

/* ── Mode navigation buttons ───────────────────────────────── */
".mode-btn {"
"  background: transparent;"
"  border: 1px solid transparent;"
"  border-radius: 6px;"
"  color: @text_dim;"
"  padding: 6px 16px;"
"  font-weight: 600;"
"  font-size: 11px;"
"  min-width: 80px;"
"}"
".mode-btn:hover {"
"  background: alpha(@accent, 0.1);"
"  color: @accent_glow;"
"  border-color: alpha(@accent, 0.3);"
"}"
".mode-active {"
"  background: alpha(@accent, 0.15);"
"  border: 1px solid @accent_dark;"
"  color: @accent;"
"  border-radius: 6px;"
"  padding: 6px 16px;"
"  font-weight: 600;"
"  font-size: 11px;"
"  min-width: 80px;"
"}"
"\n"

/* ── Action buttons ────────────────────────────────────────── */
".act-btn {"
"  background: @accent_dark;"
"  color: white;"
"  border: none;"
"  border-radius: 5px;"
"  padding: 8px 20px;"
"  font-weight: bold;"
"  font-size: 12px;"
"}"
".act-btn:hover {"
"  background: @accent;"
"}"
".act-btn:disabled {"
"  background: alpha(@accent_dark, 0.3);"
"  color: alpha(white, 0.3);"
"}"
".stop-btn {"
"  background: @danger;"
"  color: white;"
"  border: none;"
"  border-radius: 5px;"
"  padding: 8px 20px;"
"  font-weight: bold;"
"  font-size: 12px;"
"}"
".stop-btn:hover {"
"  background: lighter(@danger);"
"}"
".sec-btn {"
"  background: @bg_tertiary;"
"  color: @text_bright;"
"  border: 1px solid @border;"
"  border-radius: 5px;"
"  padding: 5px 12px;"
"  font-size: 11px;"
"}"
".sec-btn:hover {"
"  border-color: @accent;"
"  background: alpha(@accent, 0.1);"
"}"
".cp-btn {"
"  background: @bg_tertiary;"
"  color: @accent;"
"  border: 1px solid @accent_dark;"
"  border-radius: 5px;"
"  padding: 5px 14px;"
"  font-weight: bold;"
"  font-size: 11px;"
"}"
".cp-btn:hover {"
"  background: alpha(@accent, 0.2);"
"}"
".warn-btn {"
"  background: alpha(@warning, 0.15);"
"  color: @warning;"
"  border: 1px solid alpha(@warning, 0.4);"
"  border-radius: 5px;"
"  padding: 5px 12px;"
"  font-size: 11px;"
"}"
".warn-btn:hover {"
"  background: alpha(@warning, 0.25);"
"}"
"\n"

/* ── Status / info boxes ───────────────────────────────────── */
".status-box {"
"  background: @bg_secondary;"
"  border: 1px solid @border;"
"  border-radius: 8px;"
"  padding: 14px;"
"}"
".addr-lbl {"
"  background: alpha(@success, 0.08);"
"  border: 1px solid alpha(@success, 0.4);"
"  border-radius: 5px;"
"  padding: 8px 14px;"
"  font-family: monospace;"
"  font-size: 12px;"
"  color: @success;"
"}"
".fileid-lbl {"
"  background: alpha(@accent, 0.08);"
"  border: 1px solid alpha(@accent, 0.3);"
"  border-radius: 5px;"
"  padding: 8px 14px;"
"  font-family: monospace;"
"  font-size: 10px;"
"  color: @accent;"
"}"
"\n"

/* ── Drag zone ─────────────────────────────────────────────── */
".drag-zone {"
"  border: 2px dashed @border;"
"  border-radius: 10px;"
"  padding: 36px;"
"  background: alpha(@bg_tertiary, 0.4);"
"}"
".drag-zone:hover {"
"  border-color: @accent;"
"  background: alpha(@accent, 0.05);"
"}"
".drag-text {"
"  color: @text_dim;"
"  font-size: 13px;"
"}"
"\n"

/* ── Log area ──────────────────────────────────────────────── */
".log-area {"
"  background: #060612;"
"  color: #4ec9b0;"
"  font-family: \"Source Code Pro\", \"DejaVu Sans Mono\", monospace;"
"  font-size: 10px;"
"  border: 1px solid @border;"
"  border-radius: 5px;"
"  padding: 6px;"
"}"
"\n"

/* ── Tree views ────────────────────────────────────────────── */
"treeview {"
"  background: @bg_secondary;"
"  color: @text_bright;"
"}"
"treeview:selected {"
"  background: alpha(@accent, 0.25);"
"  color: white;"
"}"
"treeview header button {"
"  background: @bg_primary;"
"  color: @text_dim;"
"  border: none;"
"  border-bottom: 1px solid @border;"
"  font-weight: bold;"
"  font-size: 10px;"
"  padding: 4px 8px;"
"}"
"\n"

/* ── Progress bar ──────────────────────────────────────────── */
"progressbar trough {"
"  background: @bg_secondary;"
"  border-radius: 3px;"
"  min-height: 6px;"
"}"
"progressbar progress {"
"  background: @accent;"
"  border-radius: 3px;"
"  min-height: 6px;"
"}"
"\n"

/* ── Scrolled window / entry ───────────────────────────────── */
"scrolledwindow {"
"  border: 1px solid @border;"
"  border-radius: 5px;"
"  background: @bg_secondary;"
"}"
"entry {"
"  background: @bg_input;"
"  color: @text_bright;"
"  border: 1px solid @border;"
"  border-radius: 5px;"
"  padding: 7px 10px;"
"  font-size: 12px;"
"  caret-color: @accent;"
"}"
"entry:focus {"
"  border-color: @border_focus;"
"}"
"\n"

/* ── Labels / utility classes ──────────────────────────────── */
".sec-title {"
"  color: @text_bright;"
"  font-weight: bold;"
"  font-size: 12px;"
"}"
".dim-text {"
"  color: @text_dim;"
"  font-size: 11px;"
"}"
".stat-num {"
"  color: @accent;"
"  font-weight: bold;"
"  font-size: 16px;"
"}"
".circuit-label {"
"  color: @warning;"
"  font-size: 11px;"
"  font-family: monospace;"
"}"
".pwd-entry {"
"  background: alpha(@danger, 0.05);"
"  border: 1px solid alpha(@danger, 0.3);"
"  border-radius: 5px;"
"  padding: 7px 10px;"
"  font-size: 12px;"
"  color: @text_bright;"
"  caret-color: @danger;"
"}"
".pwd-entry:focus {"
"  border-color: @danger;"
"}"
"separator {"
"  background: @border;"
"  min-height: 1px;"
"}"
;

const char *gui_get_css_theme(void)
{
    return CSS;
}